//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.MC;

[assembly: RegisterDocumentType(ContactTopSection.CLASS_NAME, typeof(ContactTopSection))]

namespace CMS.DocumentEngine.Types.MC
{
    /// <summary>
    /// Represents a content item of type ContactTopSection.
    /// </summary>
    public partial class ContactTopSection : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "MC.ContactTopSection";


        /// <summary>
        /// The instance of the class that provides extended API for working with ContactTopSection fields.
        /// </summary>
        private readonly ContactTopSectionFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// ContactTopSectionID.
        /// </summary>
        [DatabaseIDField]
        public int ContactTopSectionID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("ContactTopSectionID"), 0);
            }
            set
            {
                SetValue("ContactTopSectionID", value);
            }
        }


        /// <summary>
        /// HeaderTitle.
        /// </summary>
        [DatabaseField]
        public string HeaderTitle
        {
            get
            {
                return ValidationHelper.GetString(GetValue("HeaderTitle"), @"");
            }
            set
            {
                SetValue("HeaderTitle", value);
            }
        }


        /// <summary>
        /// SubTitle.
        /// </summary>
        [DatabaseField]
        public string SubTitle
        {
            get
            {
                return ValidationHelper.GetString(GetValue("SubTitle"), @"");
            }
            set
            {
                SetValue("SubTitle", value);
            }
        }


        /// <summary>
        /// Description.
        /// </summary>
        [DatabaseField]
        public string Description
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Description"), @"");
            }
            set
            {
                SetValue("Description", value);
            }
        }


        /// <summary>
        /// AddressDescription.
        /// </summary>
        [DatabaseField]
        public string AddressDescription
        {
            get
            {
                return ValidationHelper.GetString(GetValue("AddressDescription"), @"");
            }
            set
            {
                SetValue("AddressDescription", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with ContactTopSection fields.
        /// </summary>
        [RegisterProperty]
        public ContactTopSectionFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with ContactTopSection fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class ContactTopSectionFields : AbstractHierarchicalObject<ContactTopSectionFields>
        {
            /// <summary>
            /// The content item of type ContactTopSection that is a target of the extended API.
            /// </summary>
            private readonly ContactTopSection mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="ContactTopSectionFields" /> class with the specified content item of type ContactTopSection.
            /// </summary>
            /// <param name="instance">The content item of type ContactTopSection that is a target of the extended API.</param>
            public ContactTopSectionFields(ContactTopSection instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// ContactTopSectionID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.ContactTopSectionID;
                }
                set
                {
                    mInstance.ContactTopSectionID = value;
                }
            }


            /// <summary>
            /// HeaderTitle.
            /// </summary>
            public string HeaderTitle
            {
                get
                {
                    return mInstance.HeaderTitle;
                }
                set
                {
                    mInstance.HeaderTitle = value;
                }
            }


            /// <summary>
            /// SubTitle.
            /// </summary>
            public string SubTitle
            {
                get
                {
                    return mInstance.SubTitle;
                }
                set
                {
                    mInstance.SubTitle = value;
                }
            }


            /// <summary>
            /// Description.
            /// </summary>
            public string Description
            {
                get
                {
                    return mInstance.Description;
                }
                set
                {
                    mInstance.Description = value;
                }
            }


            /// <summary>
            /// AddressDescription.
            /// </summary>
            public string AddressDescription
            {
                get
                {
                    return mInstance.AddressDescription;
                }
                set
                {
                    mInstance.AddressDescription = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="ContactTopSection" /> class.
        /// </summary>
        public ContactTopSection() : base(CLASS_NAME)
        {
            mFields = new ContactTopSectionFields(this);
        }

        #endregion
    }
}