//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.MC;

[assembly: RegisterDocumentType(ContactLowerSectionItem.CLASS_NAME, typeof(ContactLowerSectionItem))]

namespace CMS.DocumentEngine.Types.MC
{
    /// <summary>
    /// Represents a content item of type ContactLowerSectionItem.
    /// </summary>
    public partial class ContactLowerSectionItem : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "MC.ContactLowerSectionItem";


        /// <summary>
        /// The instance of the class that provides extended API for working with ContactLowerSectionItem fields.
        /// </summary>
        private readonly ContactLowerSectionItemFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// ContactLowerSectionItemID.
        /// </summary>
        [DatabaseIDField]
        public int ContactLowerSectionItemID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("ContactLowerSectionItemID"), 0);
            }
            set
            {
                SetValue("ContactLowerSectionItemID", value);
            }
        }


        /// <summary>
        /// Image.
        /// </summary>
        [DatabaseField]
        public string Image
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Image"), @"");
            }
            set
            {
                SetValue("Image", value);
            }
        }


        /// <summary>
        /// Badge.
        /// </summary>
        [DatabaseField]
        public bool Badge
        {
            get
            {
                return ValidationHelper.GetBoolean(GetValue("Badge"), true);
            }
            set
            {
                SetValue("Badge", value);
            }
        }


        /// <summary>
        /// Branch.
        /// </summary>
        [DatabaseField]
        public string Branch
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Branch"), @"");
            }
            set
            {
                SetValue("Branch", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with ContactLowerSectionItem fields.
        /// </summary>
        [RegisterProperty]
        public ContactLowerSectionItemFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with ContactLowerSectionItem fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class ContactLowerSectionItemFields : AbstractHierarchicalObject<ContactLowerSectionItemFields>
        {
            /// <summary>
            /// The content item of type ContactLowerSectionItem that is a target of the extended API.
            /// </summary>
            private readonly ContactLowerSectionItem mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="ContactLowerSectionItemFields" /> class with the specified content item of type ContactLowerSectionItem.
            /// </summary>
            /// <param name="instance">The content item of type ContactLowerSectionItem that is a target of the extended API.</param>
            public ContactLowerSectionItemFields(ContactLowerSectionItem instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// ContactLowerSectionItemID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.ContactLowerSectionItemID;
                }
                set
                {
                    mInstance.ContactLowerSectionItemID = value;
                }
            }


            /// <summary>
            /// Image.
            /// </summary>
            public string Image
            {
                get
                {
                    return mInstance.Image;
                }
                set
                {
                    mInstance.Image = value;
                }
            }


            /// <summary>
            /// Badge.
            /// </summary>
            public bool Badge
            {
                get
                {
                    return mInstance.Badge;
                }
                set
                {
                    mInstance.Badge = value;
                }
            }


            /// <summary>
            /// Branch.
            /// </summary>
            public string Branch
            {
                get
                {
                    return mInstance.Branch;
                }
                set
                {
                    mInstance.Branch = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="ContactLowerSectionItem" /> class.
        /// </summary>
        public ContactLowerSectionItem() : base(CLASS_NAME)
        {
            mFields = new ContactLowerSectionItemFields(this);
        }

        #endregion
    }
}