//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.MC;

[assembly: RegisterDocumentType(ContactLowerSection.CLASS_NAME, typeof(ContactLowerSection))]

namespace CMS.DocumentEngine.Types.MC
{
    /// <summary>
    /// Represents a content item of type ContactLowerSection.
    /// </summary>
    public partial class ContactLowerSection : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "MC.ContactLowerSection";


        /// <summary>
        /// The instance of the class that provides extended API for working with ContactLowerSection fields.
        /// </summary>
        private readonly ContactLowerSectionFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// ContactLowerSectionID.
        /// </summary>
        [DatabaseIDField]
        public int ContactLowerSectionID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("ContactLowerSectionID"), 0);
            }
            set
            {
                SetValue("ContactLowerSectionID", value);
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string Title
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Title"), @"");
            }
            set
            {
                SetValue("Title", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with ContactLowerSection fields.
        /// </summary>
        [RegisterProperty]
        public ContactLowerSectionFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with ContactLowerSection fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class ContactLowerSectionFields : AbstractHierarchicalObject<ContactLowerSectionFields>
        {
            /// <summary>
            /// The content item of type ContactLowerSection that is a target of the extended API.
            /// </summary>
            private readonly ContactLowerSection mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="ContactLowerSectionFields" /> class with the specified content item of type ContactLowerSection.
            /// </summary>
            /// <param name="instance">The content item of type ContactLowerSection that is a target of the extended API.</param>
            public ContactLowerSectionFields(ContactLowerSection instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// ContactLowerSectionID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.ContactLowerSectionID;
                }
                set
                {
                    mInstance.ContactLowerSectionID = value;
                }
            }


            /// <summary>
            /// Title.
            /// </summary>
            public string Title
            {
                get
                {
                    return mInstance.Title;
                }
                set
                {
                    mInstance.Title = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="ContactLowerSection" /> class.
        /// </summary>
        public ContactLowerSection() : base(CLASS_NAME)
        {
            mFields = new ContactLowerSectionFields(this);
        }

        #endregion
    }
}