//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.MC;

[assembly: RegisterDocumentType(DoctorsSection.CLASS_NAME, typeof(DoctorsSection))]

namespace CMS.DocumentEngine.Types.MC
{
    /// <summary>
    /// Represents a content item of type DoctorsSection.
    /// </summary>
    public partial class DoctorsSection : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "MC.DoctorsSection";


        /// <summary>
        /// The instance of the class that provides extended API for working with DoctorsSection fields.
        /// </summary>
        private readonly DoctorsSectionFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// DoctorsSectionID.
        /// </summary>
        [DatabaseIDField]
        public int DoctorsSectionID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("DoctorsSectionID"), 0);
            }
            set
            {
                SetValue("DoctorsSectionID", value);
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string Title
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Title"), @"");
            }
            set
            {
                SetValue("Title", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with DoctorsSection fields.
        /// </summary>
        [RegisterProperty]
        public DoctorsSectionFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with DoctorsSection fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class DoctorsSectionFields : AbstractHierarchicalObject<DoctorsSectionFields>
        {
            /// <summary>
            /// The content item of type DoctorsSection that is a target of the extended API.
            /// </summary>
            private readonly DoctorsSection mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="DoctorsSectionFields" /> class with the specified content item of type DoctorsSection.
            /// </summary>
            /// <param name="instance">The content item of type DoctorsSection that is a target of the extended API.</param>
            public DoctorsSectionFields(DoctorsSection instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// DoctorsSectionID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.DoctorsSectionID;
                }
                set
                {
                    mInstance.DoctorsSectionID = value;
                }
            }


            /// <summary>
            /// Title.
            /// </summary>
            public string Title
            {
                get
                {
                    return mInstance.Title;
                }
                set
                {
                    mInstance.Title = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="DoctorsSection" /> class.
        /// </summary>
        public DoctorsSection() : base(CLASS_NAME)
        {
            mFields = new DoctorsSectionFields(this);
        }

        #endregion
    }
}