//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.MC;

[assembly: RegisterDocumentType(HomeLowerSectionItem.CLASS_NAME, typeof(HomeLowerSectionItem))]

namespace CMS.DocumentEngine.Types.MC
{
    /// <summary>
    /// Represents a content item of type HomeLowerSectionItem.
    /// </summary>
    public partial class HomeLowerSectionItem : TreeNode
    {
        #region "Constants and variables"

        /// <summary>
        /// The name of the data class.
        /// </summary>
        public const string CLASS_NAME = "MC.HomeLowerSectionItem";


        /// <summary>
        /// The instance of the class that provides extended API for working with HomeLowerSectionItem fields.
        /// </summary>
        private readonly HomeLowerSectionItemFields mFields;

        #endregion


        #region "Properties"

        /// <summary>
        /// HomeLowerSectionItemID.
        /// </summary>
        [DatabaseIDField]
        public int HomeLowerSectionItemID
        {
            get
            {
                return ValidationHelper.GetInteger(GetValue("HomeLowerSectionItemID"), 0);
            }
            set
            {
                SetValue("HomeLowerSectionItemID", value);
            }
        }


        /// <summary>
        /// Image.
        /// </summary>
        [DatabaseField]
        public string Image
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Image"), @"");
            }
            set
            {
                SetValue("Image", value);
            }
        }


        /// <summary>
        /// Title.
        /// </summary>
        [DatabaseField]
        public string Title
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Title"), @"");
            }
            set
            {
                SetValue("Title", value);
            }
        }


        /// <summary>
        /// Description.
        /// </summary>
        [DatabaseField]
        public string Description
        {
            get
            {
                return ValidationHelper.GetString(GetValue("Description"), @"");
            }
            set
            {
                SetValue("Description", value);
            }
        }


        /// <summary>
        /// Gets an object that provides extended API for working with HomeLowerSectionItem fields.
        /// </summary>
        [RegisterProperty]
        public HomeLowerSectionItemFields Fields
        {
            get
            {
                return mFields;
            }
        }


        /// <summary>
        /// Provides extended API for working with HomeLowerSectionItem fields.
        /// </summary>
        [RegisterAllProperties]
        public partial class HomeLowerSectionItemFields : AbstractHierarchicalObject<HomeLowerSectionItemFields>
        {
            /// <summary>
            /// The content item of type HomeLowerSectionItem that is a target of the extended API.
            /// </summary>
            private readonly HomeLowerSectionItem mInstance;


            /// <summary>
            /// Initializes a new instance of the <see cref="HomeLowerSectionItemFields" /> class with the specified content item of type HomeLowerSectionItem.
            /// </summary>
            /// <param name="instance">The content item of type HomeLowerSectionItem that is a target of the extended API.</param>
            public HomeLowerSectionItemFields(HomeLowerSectionItem instance)
            {
                mInstance = instance;
            }


            /// <summary>
            /// HomeLowerSectionItemID.
            /// </summary>
            public int ID
            {
                get
                {
                    return mInstance.HomeLowerSectionItemID;
                }
                set
                {
                    mInstance.HomeLowerSectionItemID = value;
                }
            }


            /// <summary>
            /// Image.
            /// </summary>
            public string Image
            {
                get
                {
                    return mInstance.Image;
                }
                set
                {
                    mInstance.Image = value;
                }
            }


            /// <summary>
            /// Title.
            /// </summary>
            public string Title
            {
                get
                {
                    return mInstance.Title;
                }
                set
                {
                    mInstance.Title = value;
                }
            }


            /// <summary>
            /// Description.
            /// </summary>
            public string Description
            {
                get
                {
                    return mInstance.Description;
                }
                set
                {
                    mInstance.Description = value;
                }
            }
        }

        #endregion


        #region "Constructors"

        /// <summary>
        /// Initializes a new instance of the <see cref="HomeLowerSectionItem" /> class.
        /// </summary>
        public HomeLowerSectionItem() : base(CLASS_NAME)
        {
            mFields = new HomeLowerSectionItemFields(this);
        }

        #endregion
    }
}